name: Update GitHub Trophies

on:
  schedule:
    - cron: "0 1 * * *" # todo dia às 01:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Atualizado para Node 22 (LTS)

      - name: Install deps
        run: npm install

      - name: Generate trophies and stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/index.js 

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git status
          git commit -m "chore: auto update profile stats" || echo "No changes to commit"
          git pull --rebase origin main
          git push
